name: Run tests

on:
  - pull_request
  - push

jobs:
  ci:
    uses: houseabsolute/workflow-perl-dzil-ci/.github/workflows/ci.yml@v0
    with:
      dist: Specio
      with-threads: true
      ref: v0
